// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2XnQiZVj0w3eoh3LcmD_WxpH7hk-lAJQ',
    appId: '1:832066062594:web:a234ebe2acd247b7ca1a1b',
    messagingSenderId: '832066062594',
    projectId: 'tuntipankki',
    authDomain: 'tuntipankki.firebaseapp.com',
    storageBucket: 'tuntipankki.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDws8VnBMy0ahJ48DLkx1noUqimmEtpJ6E',
    appId: '1:832066062594:android:f3c410d354b526cbca1a1b',
    messagingSenderId: '832066062594',
    projectId: 'tuntipankki',
    storageBucket: 'tuntipankki.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdV4ybk7kaftC2WwOBImxhwthOQZJOFD0',
    appId: '1:832066062594:ios:23648033c7c9e5beca1a1b',
    messagingSenderId: '832066062594',
    projectId: 'tuntipankki',
    storageBucket: 'tuntipankki.firebasestorage.app',
    iosBundleId: 'com.example.tuntiPankki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdV4ybk7kaftC2WwOBImxhwthOQZJOFD0',
    appId: '1:832066062594:ios:23648033c7c9e5beca1a1b',
    messagingSenderId: '832066062594',
    projectId: 'tuntipankki',
    storageBucket: 'tuntipankki.firebasestorage.app',
    iosBundleId: 'com.example.tuntiPankki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2XnQiZVj0w3eoh3LcmD_WxpH7hk-lAJQ',
    appId: '1:832066062594:web:2146bf5a2dca834dca1a1b',
    messagingSenderId: '832066062594',
    projectId: 'tuntipankki',
    authDomain: 'tuntipankki.firebaseapp.com',
    storageBucket: 'tuntipankki.firebasestorage.app',
  );
}
